project:
  type: book
  pre-render: R/helper.R

book:
  title: "Learning Shiny"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm
  favicon: "img/favicon_io/apple-touch-icon.png"
  site-url: https://bookdown.org/pbaumgartner/learning-shiny/
  repo-url: https://github.com/petzi53/learning-shiny
  repo-branch: master
  repo-actions: [edit, issue]
  page-navigation: true

  chapters:
    - index.qmd
    - part: "Getting started"
      chapters:
        - 01-first-shiny-app.qmd
        - 02-basic-UI.qmd
        - 03-basic-reactivity.qmd
        - 04-er-injuries.qmd
    - part: "Shiny in action"
      chapters:
        - intro1.qmd
        - 05-workflow.qmd
        - 06-layouts.qmd
        - 07-graphics.qmd
        - 08-user-feedback.qmd
        - 09-uploads-downloads.qmd
  appendices:
    - 50-packages-used.qmd
    - 60-whr-exercises.qmd
    - 98-callout-boxes.qmd
    - 99-todo-list.qmd

bibliography:
    - references.bib
reference-section-title: References
# citeproc: true


format:
  html:
    theme: cosmo
    css:
     - quarto.css
     - glossary.css
    number-sections: true
    toc-depth: 5
    toc-expand: 4
    toc_float: true
    code-fold: show
    code-tools: true
    code-link: true
    code-overflow: scroll
    df-print: default

filters:
   - include-code-files
   - section-bibliographies
   - shinylive

knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor: source

execute:
    freeze: auto

lightbox: true



crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"
  custom:
    - kind: float
      reference-prefix: Important
      key: imp
    - kind: float
      reference-prefix: Commitment
      key: com
    - kind: float
      reference-prefix: Report
      key: rep
    - kind: float
      reference-prefix: Resource
      key: res
    - kind: float
      reference-prefix: Package Profile
      key: pak
    - kind: float
      reference-prefix: Bullet List
      key: bul
    - kind: float
      reference-prefix: Numerical List
      key: num
    - kind: float
      reference-prefix: Note
      key: not
    - kind: float
      reference-prefix: Explanation
      key: exp
    - kind: float
      reference-prefix: Tip
      key: tip
    - kind: float
      reference-prefix: Checklist
      key: tdo
    - kind: float
      reference-prefix: Collection Code
      key: col
    - kind: float
      reference-prefix: Watch-out
      key: wat



tip-cap-location: top
pak-cap-location: top
bul-cap-location: bottom

language:
   crossref-cnj-title: "R Code"             # replaces "Conjecture"
   crossref-cor-title: "Assessment"         # replaces "Corollary"
   crossref-def-title: "Experiment"         # replaces "Definition"
   crossref-exm-title: "Code Collection"    # replaces "Example"
#  crossref-exm-title: "Example"            # remains  "Example" (not in use, but snippet + CSS exists)
   crossref-exr-title: "Exercise"           # remains  "Exercise"
   crossref-fig-title: "Screenshot"         # replaces "Figure"
   crossref-lem-title: "Resource"           # replaces "Lemma"
   crossref-lst-title: "Listing / Output"   # replaces "Listing"
   crossref-prp-title: "Procedure"          # replaces "Proposition"
   crossref-rem-title: "Remark"             # remains  "Remark"
   crossref-sol-title: "Solution"           # remains  "Solution"
   crossref-tbl-title: "Table"              # remains  "Table"
   crossref-thm-title: "Formula"            # replaces "Theorem" (needs "formula")
#   crossref-int-title: "Interpretation"

# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
   callout-tip-title: "Tip"           # green
   callout-note-title: "Note"            # blue
   callout-warning-title: "Watch out!"   # orange
   callout-important-title: "Important"  # red
   callout-caution-title: "Caution"      # yellow
